### ISSUE TITLE
Failure on system requirement

### ISSUE THREAD

**Issue by jmbolanos** [michield/phplist-plugin-domainthrottlemap#1]
Hi, the plugin installed correctly but won't enable, stating a system requirement for phplist 3.2.4 or higher.

I'm running the latest 3.2.4 build.

John

**Comment by michield** [comment]
thanks to reporting. Can you update to see if it is resolved now?

**Comment by jmbolanos** [comment]
Yes, brilliant. Thanks!

**Comment by jmbolanos** [comment]
Does the plugin function automatically in the background or are there settings (that I can't see!). John

**Comment by michield** [comment]
there are no settings in the UI for now. It does all in the background. You need to update the code to add more mappings. The idea is that the basics are there, and if someone has time, they can improve on it.
